### ISSUE TITLE
Can't check raft model

### ISSUE THREAD

**Issue by dgryski** [ongardie/runway-model-raft#2]
Running `bin/main.js check ../runway-model-raft/raft.model` gives (after a long json dump):

`ModelingInternalError: Cannot evaluate past() without a clock value`

**Comment by ongardie-sfdc** [comment]
I think you need to do:

```
bin/main.js check --async ../runway-model-raft/raft.model
```

which should probably be the default

**Comment by dgryski** [comment]
Yup.  Working now.  (Although I killed it before the verification finished.)

(Reopen I guess if you want a bug to track making `--async` the default with `check`?)
